# Generated by Django 3.1.3 on 2020-11-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda'), ('Div', 'Dividendo'), ('Jcp', 'Juros s/ Capital')], max_length=3)),
                ('transaction_date', models.DateTimeField()),
                ('asset', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('R$', 'Reais'), ('$', 'Dolar'), ('€', 'Euro')], max_length=5)),
                ('other_costs', models.DecimalField(decimal_places=5, max_digits=8)),
                ('desc_1', models.CharField(max_length=20)),
                ('desc_2', models.CharField(max_length=100)),
                ('stockbroker', models.CharField(choices=[('XP', 'XP Investimentos'), ('CL', 'Clear'), ('RI', 'Rico'), ('AV', 'Avenue'), ('TD', 'TD Ameritrade')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
