# Generated by Django 3.1.3 on 2020-11-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('R$', 'Reais'), ('$', 'Dolar'), ('€', 'Euro')], default='R$', max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='desc_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='desc_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='other_costs',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stockbroker',
            field=models.CharField(choices=[('CL', 'Clear'), ('XP', 'XP Investimentos'), ('RI', 'Rico'), ('AV', 'Avenue'), ('TD', 'TD Ameritrade')], default='CL', max_length=2, null=True),
        ),
    ]
