# Generated by Django 3.1.3 on 2020-11-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201112_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='desc_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='desc_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='other_costs',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stockbroker',
            field=models.CharField(blank=True, choices=[('CL', 'Clear'), ('XP', 'XP Investimentos'), ('RI', 'Rico'), ('AV', 'Avenue'), ('TD', 'TD Ameritrade')], max_length=2),
        ),
    ]
