# Generated by Django 3.1.3 on 2020-11-15 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20201113_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('ticker', models.CharField(max_length=7, unique=True)),
                ('desc_1', models.CharField(blank=True, max_length=20, null=True)),
                ('desc_2', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_3', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.assettype')),
            ],
        ),
        migrations.CreateModel(
            name='Fiis',
            fields=[
            ],
            options={
                'managed': False,  # Make it unmanaged
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portfolio.asset',),
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
            ],
            options={
                'managed': False,  # Make it unmanaged
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portfolio.asset',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='asset_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.assettype'),
        ),
    ]
