# Generated by Django 3.1.3 on 2020-11-23 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioConsolidated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=12)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('result_currency', models.DecimalField(decimal_places=2, max_digits=12)),
                ('result_percentage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_dividend', models.DecimalField(decimal_places=2, max_digits=12)),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.assettype')),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
        migrations.DeleteModel(
            name='Fiis',
        ),
        migrations.DeleteModel(
            name='fiitransaction',
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
        migrations.DeleteModel(
            name='stocktransaction',
        ),
        migrations.CreateModel(
            name='FiiTransaction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portfolio.transaction',),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portfolio.transaction',),
        ),
    ]
