# Generated by Django 3.1.3 on 2020-11-23 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20201123_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioconsolidated',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
