# Generated by Django 3.1.3 on 2020-11-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_portfolioconsolidated_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='unit_cost',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
