# Generated by Django 3.1.3 on 2020-11-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20201124_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='consolidated',
            field=models.BooleanField(default=False),
        ),
    ]
