# Generated by Django 3.1.3 on 2020-12-03 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_portfolio_consolidated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='type',
            new_name='type_investment',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='type_transaction',
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='portfolioconsolidated',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='asset_type',
        ),
        migrations.AlterField(
            model_name='assettype',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolioconsolidated',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.asset'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.asset'),
        ),
    ]
