# Generated by Django 3.1.3 on 2020-12-03 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20201203_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type_investment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portfolio.assettype'),
            preserve_default=False,
        ),
    ]
