# Generated by Django 3.1.3 on 2020-12-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_transaction_type_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
