# Generated by Django 3.1.3 on 2021-02-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210226_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.CharField(choices=[('R$', 'Real'), ('$', 'Dollar'), ('€', 'Euro')], default='R$', max_length=5),
        ),
        migrations.AlterField(
            model_name='portfolioassetconsolidated',
            name='currency',
            field=models.CharField(choices=[('R$', 'Real'), ('$', 'Dollar'), ('€', 'Euro')], default='R$', max_length=5),
        ),
        migrations.AlterField(
            model_name='portfolioconsolidated',
            name='currency',
            field=models.CharField(choices=[('R$', 'Real'), ('$', 'Dollar'), ('€', 'Euro')], default='R$', max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('R$', 'Real'), ('$', 'Dollar'), ('€', 'Euro')], default='R$', max_length=5),
        ),
    ]
