# Generated by Django 3.2.3 on 2021-05-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210226_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type_investment',
        ),
        migrations.AddField(
            model_name='portfolioassetconsolidated',
            name='cache_key',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='portfolioconsolidated',
            name='cache_key',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type_investment',
            field=models.CharField(choices=[('FII', 'Fii'), ('STOCK', 'Stock')], max_length=5),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_portfolio_name'),
        ),
    ]
